CREATE TABLE IF NOT EXISTS volunteers (id INTEGER PRIMARY KEY AUTOINCREMENT, public_ref TEXT UNIQUE, submission_id TEXT NOT NULL UNIQUE, first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, status TEXT NOT NULL DEFAULT 'NEW', skills_text TEXT, accommodation_text TEXT, additional_note TEXT, privacy_consent INTEGER NOT NULL DEFAULT 0, privacy_consent_version TEXT NOT NULL, privacy_consent_at TEXT NOT NULL, updates_consent INTEGER NOT NULL DEFAULT 0, source TEXT NOT NULL DEFAULT 'website', last_contact_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, archived_at TEXT, CHECK (status IN ('NEW','REVIEWED','CONTACTED','APPROVED','ACTIVE','INACTIVE','DECLINED','ARCHIVED')));
CREATE INDEX IF NOT EXISTS idx_volunteers_status ON volunteers (status);
CREATE INDEX IF NOT EXISTS idx_volunteers_email ON volunteers (email);
CREATE INDEX IF NOT EXISTS idx_volunteers_created_at ON volunteers (created_at);
CREATE INDEX IF NOT EXISTS idx_volunteers_archived ON volunteers (archived_at);
CREATE TABLE IF NOT EXISTS volunteer_interests (volunteer_id INTEGER NOT NULL, interest_code TEXT NOT NULL, PRIMARY KEY (volunteer_id, interest_code), FOREIGN KEY (volunteer_id) REFERENCES volunteers(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_interests_code ON volunteer_interests (interest_code);
CREATE TABLE IF NOT EXISTS volunteer_availability (volunteer_id INTEGER NOT NULL, availability_code TEXT NOT NULL, PRIMARY KEY (volunteer_id, availability_code), FOREIGN KEY (volunteer_id) REFERENCES volunteers(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_availability_code ON volunteer_availability (availability_code);
CREATE TABLE IF NOT EXISTS volunteer_notes (id INTEGER PRIMARY KEY AUTOINCREMENT, volunteer_id INTEGER NOT NULL, note TEXT NOT NULL, created_by TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY (volunteer_id) REFERENCES volunteers(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_notes_volunteer ON volunteer_notes (volunteer_id, created_at);
CREATE TABLE IF NOT EXISTS communications (id INTEGER PRIMARY KEY AUTOINCREMENT, volunteer_id INTEGER NOT NULL, type TEXT NOT NULL, direction TEXT NOT NULL DEFAULT 'OUTBOUND', to_address TEXT NOT NULL, subject TEXT, body_preview TEXT, status TEXT NOT NULL DEFAULT 'PENDING', provider_id TEXT, error_message TEXT, attempts INTEGER NOT NULL DEFAULT 0, created_by TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY (volunteer_id) REFERENCES volunteers(id) ON DELETE CASCADE, CHECK (status IN ('PENDING','SENT','FAILED','RETRIED')));
CREATE INDEX IF NOT EXISTS idx_comms_volunteer ON communications (volunteer_id, created_at);
CREATE INDEX IF NOT EXISTS idx_comms_status ON communications (status);
CREATE TABLE IF NOT EXISTS audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, actor TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_log (entity_type, entity_id);
CREATE TABLE IF NOT EXISTS admin_users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, display_name TEXT, role TEXT NOT NULL DEFAULT 'VIEWER', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, CHECK (role IN ('OWNER','ADMIN','COORDINATOR','VIEWER')));
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT, updated_at TEXT NOT NULL);
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES ('privacy_consent_version', '2026-08-v1', datetime('now')), ('public_ref_prefix', 'CPF-VOL', datetime('now')), ('stale_review_days', '7', datetime('now'));
