name = "community-pulse-foundation"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "community-pulse-foundation.atoyejet.workers.dev/*", zone_name = "atoyejet.workers.dev" }
]

[build]
command = "echo 'Ready'"

[[assets.bindings]]
path = "/"
directory = "./"
